FROM node:18

WORKDIR /app

# Copy package.json and install dependencies
COPY package.json .
RUN npm install

# Copy the rest of the application files
COPY . .
# Build the application
RUN npm run build

EXPOSE 5000

# Command to run Vite with custom host and port
CMD ["npm", "run", "preview"]